version: "3.9"
services:
  database:
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=AhzeiP5s
      - MYSQL_DATABASE=omeka
      - MYSQL_USER=omeka
      - MYSQL_PASSWORD=xie7Hiuf
  omeka-s:
    image: raboof/omeka-s:latest
    links:
      - database
    environment:
      - APPLICATION_ENV=development
      - OMEKA_CONNECTION_URL=mysql://omeka:xie7Hiuf@database/omeka
    ports:
      # When these don't match, set file_store/local/base_uri
      # to http://yourdomain/files to make URL's for uploaded
      # images work:
      - "8080:8080"
    volumes:
      - ./config:/webroot/config
      - ./logs:/webroot/logs
      - ./files:/webroot/files
